// Generated by CoffeeScript 1.3.3
(function() {
  var HEIGHT, WIDTH;

  importScripts('numeric-1.2.6.min.js');

  importScripts('quaternion.js');

  importScripts('lambert.js');

  importScripts('orbit.js');

  WIDTH = 300;

  HEIGHT = 300;

  this.onmessage = function(event) {
    var arrivalTime, deltaV, deltaVs, departureTime, destinationOrbit, earliestDeparture, finalOrbitalVelocity, i, initialOrbitalVelocity, lastProgress, maxDeltaV, minDeltaV, minDeltaVPoint, n1, n2, now, originOrbit, originPositions, originVelocities, p1, p2, referenceBody, shortestTimeOfFlight, timeOfFlight, transfer, transferType, trueAnomaly, v1, v2, x, xResolution, y, yResolution, _i, _j, _k;
    transferType = event.data.transferType;
    originOrbit = Orbit.fromJSON(event.data.originOrbit);
    initialOrbitalVelocity = event.data.initialOrbitalVelocity;
    destinationOrbit = Orbit.fromJSON(event.data.destinationOrbit);
    finalOrbitalVelocity = event.data.finalOrbitalVelocity;
    earliestDeparture = event.data.earliestDeparture;
    shortestTimeOfFlight = event.data.shortestTimeOfFlight;
    xResolution = event.data.xScale / WIDTH;
    yResolution = event.data.yScale / HEIGHT;
    referenceBody = originOrbit.referenceBody;
    n1 = originOrbit.normalVector();
    n2 = destinationOrbit.normalVector();
    originPositions = [];
    originVelocities = [];
    for (x = _i = 0; 0 <= WIDTH ? _i < WIDTH : _i > WIDTH; x = 0 <= WIDTH ? ++_i : --_i) {
      departureTime = earliestDeparture + x * xResolution;
      trueAnomaly = originOrbit.trueAnomalyAt(departureTime);
      originPositions[x] = originOrbit.positionAtTrueAnomaly(trueAnomaly);
      originVelocities[x] = originOrbit.velocityAtTrueAnomaly(trueAnomaly);
    }
    deltaVs = new Float64Array(WIDTH * HEIGHT);
    i = 0;
    minDeltaV = Infinity;
    maxDeltaV = 0;
    lastProgress = 0;
    for (y = _j = 0; 0 <= HEIGHT ? _j < HEIGHT : _j > HEIGHT; y = 0 <= HEIGHT ? ++_j : --_j) {
      timeOfFlight = shortestTimeOfFlight + ((HEIGHT - 1) - y) * yResolution;
      for (x = _k = 0; 0 <= WIDTH ? _k < WIDTH : _k > WIDTH; x = 0 <= WIDTH ? ++_k : --_k) {
        departureTime = earliestDeparture + x * xResolution;
        arrivalTime = departureTime + timeOfFlight;
        p1 = originPositions[x];
        v1 = originVelocities[x];
        trueAnomaly = destinationOrbit.trueAnomalyAt(arrivalTime);
        p2 = destinationOrbit.positionAtTrueAnomaly(trueAnomaly);
        v2 = destinationOrbit.velocityAtTrueAnomaly(trueAnomaly);
        transfer = Orbit.transfer(transferType, referenceBody, departureTime, p1, v1, n1, arrivalTime, p2, v2, n2, initialOrbitalVelocity, finalOrbitalVelocity);
        deltaVs[i++] = deltaV = transfer.deltaV;
        if (deltaV < minDeltaV) {
          minDeltaV = deltaV;
          minDeltaVPoint = {
            x: x,
            y: y
          };
        }
        maxDeltaV = Math.max(deltaV, maxDeltaV);
      }
      now = Date.now();
      if (now - lastProgress > 100) {
        postMessage({
          progress: (y + 1) / HEIGHT
        });
        lastProgress = now;
      }
    }
    try {
      return postMessage({
        deltaVs: deltaVs.buffer,
        minDeltaV: minDeltaV,
        minDeltaVPoint: minDeltaVPoint,
        maxDeltaV: maxDeltaV
      }, [deltaVs.buffer]);
    } catch (error) {
      return postMessage({
        deltaVs: deltaVs,
        minDeltaV: minDeltaV,
        minDeltaVPoint: minDeltaVPoint,
        maxDeltaV: maxDeltaV
      });
    }
  };

}).call(this);
